import webpush from 'npm:web-push@3.6.7'; import { createClient } from 'npm:@supabase/supabase-js@2';
const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
async function cfg(){const {data,error}=await db.from('to_you_push_config').select('vapid_public,vapid_private,cron_secret').eq('id',true).maybeSingle();if(error||!data)throw new Error('Push configuration unavailable');webpush.setVapidDetails('mailto:notifications@amanah.app',data.vapid_public,data.vapid_private);return data;}
async function push(userId:string,title:string,body:string,tag:string){const {data:subs,error}=await db.from('push_subscriptions').select('id,endpoint,p256dh,auth').eq('user_id',userId);if(error)throw error;let sent=0;for(const sub of subs||[]){try{await webpush.sendNotification({endpoint:sub.endpoint,keys:{p256dh:sub.p256dh,auth:sub.auth}},JSON.stringify({title,body,tag,icon:'./icon-v2.svg',badge:'./icon-v2.svg'}));sent++;}catch(e){const c=(e as any)?.statusCode;if(c===404||c===410)await db.from('push_subscriptions').delete().eq('id',sub.id);}}return sent;}
function parts(d:Date,tz:string){const a=new Intl.DateTimeFormat('en-US',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',weekday:'short',hour12:false}).formatToParts(d),g=(t:string)=>a.find(x=>x.type===t)?.value||'';return {y:+g('year'),m:+g('month'),d:+g('day'),h:+g('hour'),min:+g('minute'),w:g('weekday')};}
const key=(p:any)=>`${p.y}-${String(p.m).padStart(2,'0')}-${String(p.d).padStart(2,'0')}`,wi=(w:string)=>({Sun:0,Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6} as any)[w]??0;
function due(h:any,p:any){const f=String(h.frequency||'daily').toLowerCase(),ds=Array.isArray(h.target_days)?h.target_days.map(Number):[];return f==='daily'||(f==='weekly'?(ds.length?ds.includes(wi(p.w)):true):f==='custom'?ds.includes(wi(p.w)):true);}
async function streak(now:Date){const {data:ps,error}=await db.from('profiles').select('id,timezone,notifications').eq('notifications',true);if(error)throw error;let sent=0;for(const p0 of ps||[]){let p;try{p=parts(now,p0.timezone||'UTC')}catch{p=parts(now,'UTC')}if(p.h!==20||p.min>10)continue;const day=key(p);const {data:hs}=await db.from('habits').select('id,name,title,frequency,target_days').eq('user_id',p0.id).eq('is_active',true).eq('archived',false);for(const h of hs||[]){if(!due(h,p))continue;const {data:done}=await db.from('habit_completions').select('id').eq('habit_id',h.id).eq('owner_user_id',p0.id).eq('completed_on',day).limit(1);if(done?.length)continue;const existing=await db.from('streak_warning_logs').select('id').eq('user_id',p0.id).eq('habit_id',h.id).eq('warning_date',day).maybeSingle();if(existing.data)continue;const log=await db.from('streak_warning_logs').insert({user_id:p0.id,habit_id:h.id,warning_date:day});if(log.error)continue;sent+=await push(p0.id,'🔥 Streak at risk',`${h.name||h.title||'Your habit'} is still incomplete today. Complete it before the day ends to protect your streak.`,'to-you-streak-'+h.id+'-'+day);}}return sent;}
Deno.serve(async req=>{if(req.method!=='POST')return new Response('Method not allowed',{status:405});try{const c=await cfg();if(req.headers.get('x-to-you-cron-secret')!==c.cron_secret)return Response.json({error:'Unauthorized'},{status:401});const now=new Date();const {data:rows,error}=await db.from('notification_schedules').select('*').eq('enabled',true).lte('notify_at',now.toISOString()).order('notify_at',{ascending:true}).limit(100);if(error)throw error;let processed=0,sent=0;for(const n of rows||[]){sent+=await push(n.user_id,n.title,n.body||'','to-you-schedule-'+n.id);processed++;const d=new Date(n.notify_at);let next=null;if(n.repeat_daily){d.setUTCDate(d.getUTCDate()+1);next=d}else if(n.repeat_yearly){d.setUTCFullYear(d.getUTCFullYear()+1);next=d}if(next)await db.from('notification_schedules').update({notify_at:next.toISOString(),last_sent_at:now.toISOString(),updated_at:now.toISOString()}).eq('id',n.id);else await db.from('notification_schedules').update({enabled:false,last_sent_at:now.toISOString(),updated_at:now.toISOString()}).eq('id',n.id);}return Response.json({ok:true,processed,sent,streakSent:await streak(now)});}catch(e){return Response.json({error:String((e as Error)?.message||e)},{status:500});}});
